# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.cache/wt [current_project]
set_property parent.project_path G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths {
  g:/studia/fpga/project_sdup_ocr/ip_repo/neural_network_1.1
  g:/studia/fpga/project_sdup_ocr/ip_repo/neural_network_1.0
} [current_project]
set_property ip_output_repo g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/hdl/design_ocr_wrapper.v
add_files G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/design_ocr.bd
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_processing_system7_0_1/design_ocr_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_xbar_1/design_ocr_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/ip/design_ocr_auto_pc_0/design_ocr_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/bd/design_ocr/design_ocr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_ocr_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_ocr_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_ocr_wrapper_utilization_synth.rpt -pb design_ocr_wrapper_utilization_synth.pb"
