# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_ocr/design_ocr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr || ORIG_REF_NAME==design_ocr} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_processing_system7_0_1/design_ocr_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_processing_system7_0_1 || ORIG_REF_NAME==design_ocr_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_neural_network_0_1/design_ocr_neural_network_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_neural_network_0_1 || ORIG_REF_NAME==design_ocr_neural_network_0_1} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_axi_gpio_0_4 || ORIG_REF_NAME==design_ocr_axi_gpio_0_4} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_ps7_0_axi_periph_1/design_ocr_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_ocr_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_ocr_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_xbar_1/design_ocr_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_xbar_1 || ORIG_REF_NAME==design_ocr_xbar_1} -quiet] -quiet

# IP: bd/design_ocr/ip/design_ocr_auto_pc_0/design_ocr_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ocr_auto_pc_0 || ORIG_REF_NAME==design_ocr_auto_pc_0} -quiet] -quiet

# XDC: bd/design_ocr/ip/design_ocr_processing_system7_0_1/design_ocr_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ocr_processing_system7_0_1 || ORIG_REF_NAME==design_ocr_processing_system7_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ocr_axi_gpio_0_4 || ORIG_REF_NAME==design_ocr_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4_ooc.xdc

# XDC: bd/design_ocr/ip/design_ocr_axi_gpio_0_4/design_ocr_axi_gpio_0_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ocr_axi_gpio_0_4 || ORIG_REF_NAME==design_ocr_axi_gpio_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ocr_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_ocr_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ocr_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_ocr_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_ocr/ip/design_ocr_rst_ps7_0_50M_0/design_ocr_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/design_ocr/ip/design_ocr_xbar_1/design_ocr_xbar_1_ooc.xdc

# XDC: bd/design_ocr/ip/design_ocr_auto_pc_0/design_ocr_auto_pc_0_ooc.xdc

# XDC: bd/design_ocr/design_ocr_ooc.xdc
