# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.cache/wt [current_project]
set_property parent.project_path G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths {
  g:/studia/fpga/project_sdup_ocr/ip_repo/neural_network_1.1
  g:/studia/fpga/project_sdup_ocr/ip_repo/neural_network_1.0
} [current_project]
set_property ip_output_repo g:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/imports/new/neuron_layer1_rtl.sv
  G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/imports/new/neuron_layer2_rtl.sv
  G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/imports/new/neuron_layer3_rtl.sv
  G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/imports/new/neuron_layer4_rtl.sv
  G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/sources_1/imports/new/network_rtl.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/constrs_1/new/zedboard_master.xdc
set_property used_in_implementation false [get_files G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.srcs/constrs_1/new/zedboard_master.xdc]


synth_design -top network_rtl -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef network_rtl.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file network_rtl_utilization_synth.rpt -pb network_rtl_utilization_synth.pb"
