webtalk_init -webtalk_dir G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.sim/sim_1/behav/xsim/xsim.dir/single_neuron_test_tb_rtl_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 18 20:30:09 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "29923_4263_1462473138_723" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f75c31a5-8c09-42c5-a23e-8f25d5b4c360" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "05e7eb624244473499a814d600c6f3d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "106" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "21 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2489421568 -regid "29923_4263_1462473138_723" -xml G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.sim/sim_1/behav/xsim/xsim.dir/single_neuron_test_tb_rtl_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.sim/sim_1/behav/xsim/xsim.dir/single_neuron_test_tb_rtl_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/studia/fpga/project_sdup_ocr/OCR_FPGA/OCR_FPGA.sim/sim_1/behav/xsim/xsim.dir/single_neuron_test_tb_rtl_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
